baseURL = "https://buildrobotz.com"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "BuildRobotZ"
#googleAnalytics = "G-74QS6QP8PQ"
#disqusShortname = "merrysprout"
disqusShortname = "buildrobotz"

[params]
logo = "banner/BuildRobotZ-logo-lg-white.png"
copyright = " www.buildrobotz.com"
tagline = "Inspiring roboticist"
bannerPath = "/banner/"
readingTime = true
wordCount = false
staticMan = true
enableRobotsTXT = true
Paginate = 6


comments = true
socialShare = true
PostsAsRows = false
hideAuthor = true
showRelatedPosts = true
[Author]
name = "Srini Vijay"
