baseURL = "https://blog.buildrobotz.com"
languageCode = "en-us"
title = "BuildRobotZ"
#googleAnalytics = "G-74QS6QP8PQ"
disqusShortname = "merrysprout"

[params]
logo = "banner/BuildRobotZ-logo-lg-white.png"
copyright = " www.buildrobotz.com"
tagline = "Inspiring roboticist"
banners="/content/banner/"

