baseURL = "https://blog.buildrobotz.com"
languageCode = "en-us"
title = "BuildRobotZ"
googleAnalytics = "UA-164308157-1"
disqusShortname = "merrysprout"

[params]
logo = "banner/merrysprout-logo.png"
copyright = "www.buildrobotz.com"
tagline = "Inspiring roboticist"
banners="/content/banner/"

